"use client";
import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/navbar/NavBar";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar
          navLinks={[
            {
              placeholder: "Dashboard",
              link: "/dashboard",
            },
            {
              placeholder: "Sign In",
              link: "/api/auth/signin?callback=/",
            },
            {
              placeholder: "Sign Out",
              link: "/api/auth/signout?callback=/",
            },
          ]}
        />
        <br />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
